name: Twice Daily Streamlit Update Trigger

on:
  schedule:
    - cron: '3 3 * * *'   # ⏰ 9:03 AM IST
    - cron: '33 9 * * *'  # ⏰ 3:33 PM IST
  workflow_dispatch:

jobs:
  hit-streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Streamlit App Daily Update (mode 772001)
        run: |
          curl --retry 5 --retry-delay 10 "https://proinvest.streamlit.app/?mode=772001"
